### PR TITLE
chore: remove unused config files

### LINKED ISSUE #142: Clean up unused files and services from the repo
After migration from Sourcify, there are some files not used in the repo, _i.e._, related to monitor, IPFS, environments, and more. Review and remove unused files to avoid cluttering the repo and any future confusion.

### PR DESCRIPTION
**Pull request by acuarica**
**Description**:

This PR cleans up the repo by removing unused files coming from Sourcify.

- [x] `.circleci` this is used by upstream Sourcify, not us
 `.vscode` and `ui/.vscode` unused launch configurations
 `tslint.json` old lint settings, superseded by `.eslintrc.js` f855a1c8afe2a5f2ba33ed2032820256b8c6a2c0
- [x] `services/ipfs` unused image, see https://docs.sourcify.dev/docs/repository/#ipfs
 `services/s3sync` unused image, see https://docs.sourcify.dev/docs/repository/#s3-bucket
  some files from `scripts/` that might be used by upstream Sourcify 78c4de96a43185c0f30332abf400b2ffa00a55fe, 93b5dde8474a2815471008833913105fff237b60 and ca75ec271b869aa377c3aa6fd7b42ceb9cd718ad
- [x] `.github/PULL_REQUEST_TEMPLATE/release.md` unused PR template ad266cd2c2613da34162b7f6ff44ac03ab686cf5
- [x] `scripts/hedera-reset-(previewnet|testnet).sh` invoke `hedera-reset.sh` directly from `package.json`'s `scripts` to avoid indirection and `scripts` folder pollution 9de95dd02ed60c8b3bec20d5df126ff6ccde2436
- [x] `environments/(build-)?(ipfs|monitor|s3).yaml` docker related configs for unused services a61b2eb056374f1432670213378584ac6aab17e3
- [x] `monitor` service related files c04daf26cc33f7a1da10e05001a37a7430e73608
- [x] `environments/(grafana|loki-config|promtail-config).yaml` satellite service configs 0740bc22a843852fe89f51312248ade617e32010
- [x] `environments/(repository|server|ui).yaml` Hedera `compose` configs superseded by `docker-compose-hedera.yaml` b8068f7a48a4ad2c865190e41172e23e1d69906b
- [x] `environments/.env.(dev|latest|stable)` upstream Sourcify `.env` config files not used by Hedera 51eed0e808890efc95bc0a4f1da3dd9f76f3688b
- [x] `environments/.env.secrets.gpg` unused secrets b3fe1009fe9f0acf8b65401854a26b5ec2192840 and related config files 8fa438d
- [x] `ui/.env.(development|production)` old env var templates and update `ui/.gitignore` accordingly 99a009a

This PR is a pre-step towards issue #147, where upstream Sourcify images will be consumed directly (_except `ui`_).

The `ui`'s landing page is also unused and needs to be removed. However, because removing a page would also require updating the `ui/package.json`'s dependencies, its removal is implemented as part of #160.

**Related issue(s)**:

Fixes #142.

**Notes for reviewer**:

The amount of files removed in this PR got larger then I expected. As a recommendation, it might be easier for reviewers to look at each commit individually. Moreover, next to each item is the commit that delete it.

### CODE REVIEW

**Comment by acuarica** [comment]
@svienot @rustyShacklefurd I would like your input here, is there something else we should remove?

**Comment by svienot** [comment]
> @svienot @rustyShacklefurd I would like your input here, is there something else we should remove?

This looks good.
I guess we might as well get rid of a couple more scripts:
 - decrypt.sh
 - encrypt.sh
 - find_replace.sh

**Comment by acuarica** [comment]
@svienot @rustyShacklefurd when you have a bit of time, please take a look at this PR, thanks.

**Review by svienot — APPROVED** [review]
Looks good (nice clean-up) !

**Pull request merged**
