### PR TITLE
fix: repository lookup select contract form

### LINKED ISSUE #91: Hedera Sourcify search views have different behavior
### Description

The search tool from the following link does not work as expected: 
https://repository-verify.hashscan.io/select-contract/ 

See repro steps below for details.

### Steps to reproduce

- Contract address: 0x00000000000000000000000000000000002e7a5d
- HashScan View (Partial Match ✅): https://hashscan.io/mainnet/contract/0.0.3045981

- Search result from this view: https://verify.hashscan.io/#/lookup
image

- Search result from this view: https://repository-verify.hashscan.io/select-contract/
image

For clarity, the verification results exist in Hedera Sourcify: https://repository-verify.hashscan.io/contracts/partial_match/295/0x00000000000000000000000000000000002E7A5D/

**The search functionality from one of the views is what is broken.**

### Additional context

_No response_

### Hedera network

mainnet, testnet

### Version

Latest

### Operating system

macOS

### PR DESCRIPTION
**Pull request by acuarica**
**Description**:

Use checksummed address lookup in the repository `select-contract-form`. This allows the user to use the form with non-checksummed addresses.

**Related issue(s)**:

Fixes #91 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by acuarica** [comment]
@Nana-EC @svienot The PR diff looks like a lot has changed, but I only added some lines in `App.js` and `package.json`. This is because IntelliJ reordered the files within the patch.

Shall we use a different approach, _e.g._, `git diff` to generate the patch consistently?

**Review by Nana-EC — APPROVED** [review]
LG

**Review by svienot — APPROVED** [review]
Looks good, works well.

**Comment by acuarica** [comment]
> Looks good, works well.

@svienot just to double-check, did you manage to verify that this PR works as expected? Applying the patch, building the image and make a lookup in the repository?

If that's the case, I will go ahead and merge this. I wasn't able to verify it myself because of https://github.com/hashgraph/hedera-sourcify/issues/103.

**Comment by svienot** [comment]
@acuarica yes I did check this. We should be good to go.

**Pull request merged**
